[package]
name = "tube-game-solver-rs"
version = "0.1.0"
authors = ["Chris Sinjakli <chris@sinjakli.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libgame"

[dependencies]
